#!/usr/bin/env bash
# install-cron.sh — install/refresh /etc/cron.d/jobs-cz entry on Flash.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
CRON_FILE=/etc/cron.d/jobs-cz

cat > "$CRON_FILE" <<EOF
# jobs.cz daily refresh — runs all saved searches, ntfy push on diff
# Generated by install-cron.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# 06:30 each morning — Filip's saved searches scrape
30 6 * * * root $ROOT/scripts/refresh-all.sh > /dev/null 2>&1
EOF

chmod 644 "$CRON_FILE"
echo "[OK] $CRON_FILE installed:"
cat "$CRON_FILE"
